from __future__ import annotations

from decouple import config as env

FERNET_SECRET_KEY = env('FERNET_SECRET_KEY')
FLASK_SECRET_KEY = env('FLASK_SECRET_KEY')
MASSIVE_USER_BY_COMPANY_SECRET_PASSPHRASE = env('MASSIVE_USER_BY_COMPANY_SECRET_PASSPHRASE')
DB_NAME = env('DB_NAME')
DB_USERNAME = env('DB_USERNAME')
DB_PASSWORD = env('DB_PASSWORD')
MONGODB_HOST = env('MONGODB_HOST')
MONGODB_PORT = env('MONGODB_PORT')
MONGO_CLUSTER_CONN = env('MONGO_CLUSTER_CONN')

CONTENT_TYPE = env('CONTENT_TYPE')
PLATFORM = env('PLATFORM')
VERSION = env('VERSION')
OS = env('OS')
DEVICE = env('DEVICE')

TOWER_BASE_URL = env('TOWER_BASE_URL')

TOWER_AUTH_EMAIL = env('TOWER_AUTH_EMAIL')
TOWER_AUTH_PASSWORD = env('TOWER_AUTH_PASSWORD')
